name: ECS Starter CD Develop

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Get branch name
      id: vars
      run: echo ::set-output name=stage::${GITHUB_REF#refs/*/}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: simple_whale_demo
        AWS_REGION: ${{ secrets.AWS_REGION }}
        IMAGE_TAG: ${{ github.sha }}        
        ECS_TASK_DEFINITION: ./task-definition/dev.json
      run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    
    - name: List files
      run: ls -R

    - name: Render Amazon ECS task definition
      # Fill in the new image ID in the Amazon ECS task definition
      id: simple_whale_demo-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition:  ./task-definition/dev.json #mywhaleapp.json
        container-name: simple_whale_demo
        image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG #${{ steps.build-image.outputs.image }}
    
    - name: List files
      run: ls -R

    - name: Deploy to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: simple_whale_demo
        #task-definition: ${{ steps.simple_whale_demo-container.outputs.task-definition }}
        #service: simple_whale_demo-service
        cluster: fargate-cluster
        wait-for-service-stability: true

    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}